name: Publish package snapshot

on:
  push:
    branches:
      - "jan/github-actions"
  # This workflow can be triggered from the UI
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: Install Dependencies
        id: install
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Build package
        id: build
        run: yarn build

      - name: Publish snapshot versions
        # We'll publish the version under snapshot tag
        # This is important since we don't want to be publishing under latest
        run: yarn lerna publish from-package --yes --preid dev-${{ github.sha }} --pre-dist-tag dev
