name: Release

on:
  push:
    branches:
      - main
      - 'release/**'

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  # We require the NPM_TOKEN env variable to be set when installing dependencies
  # and for several other jobs so we keep it global
  # FIXME Remove after testing
  # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NPM_TOKEN: xxxxxx

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Build Packages
        run: yarn build

      - name: Test
        run: yarn test

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            packages/*/dist/

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Publish to NPM
        run: yarn publish:main --yes